#!/bin/sh

# export LIBAROMA_GCC="gcc -mfpmath=sse -mmmx -msse -msse2 -msse3 -msse4.2"
# export LIBAROMA_GPP="g++ -mfpmath=sse -mmmx -msse -msse2 -msse3 -msse4.2"


export LIBAROMA_GCC="gcc -DFT2_NO_HARFBUZZ=1 -DLIBAROMA_TTY_KDSETMODE=1 -DLIBAROMA_CONFIG_NOFONT_SUBPIXEL=1"
export LIBAROMA_GPP="g++ -DFT2_NO_HARFBUZZ=1 -DLIBAROMA_TTY_KDSETMODE=1 -DLIBAROMA_CONFIG_NOFONT_SUBPIXEL=1"

# export LIBAROMA_CFLAGS="-Wno-sign-compare -Wno-unused-variable -O3 -fopenmp -DLIBAROMA_CONFIG_OPENMP=1 -DLIBAROMA_TTY_KDSETMODE=1 -DLIBAROMA_CONFIG_NOFONT_SUBPIXEL=1"
# export LIBAROMA_DEBUG_CFLAGS="-Wno-sign-compare -Wno-unused-variable -ggdb -fopenmp -DLIBAROMA_CONFIG_OPENMP=1 -DLIBAROMA_TTY_KDSETMODE=1 -DLIBAROMA_CONFIG_NOFONT_SUBPIXEL=1"

export LIBAROMA_CFLAGS=""
export LIBAROMA_DEBUG_CFLAGS=""

export LIBAROMA_PATH="/home/amarullz/_libaroma"
export LIBAROMA_CONFIG_DEBUG="3"
export LIBAROMA_CONFIG_DEBUG_FILE="0"
export LIBAROMA_CONFIG_DEBUG_MEMORY="0"
export LIBAROMA_CONFIG_COMPILER_MESSAGE="1"
export LIBAROMA_CONFIG_SHMEMFB="0"

bash
